CONSTANT_DEPTH_FORCE: 30
CONSTANT_REVERSE_EFFORT: 0
X_D: 2.5
X_I: 1.75
X_I_LIMIT: 4
X_MAX_ACTUATION: 50
X_MIN_ACTUATION: -50
X_P: 32
Y_D: 2.5
Y_I: 1.75
Y_I_LIMIT: 4
Y_MAX_ACTUATION: 50
Y_MIN_ACTUATION: -50
Y_P: 32
Z_D: 15
Z_I: 2
Z_I_LIMIT: 2
Z_MAX_ACTUATION: 60
Z_MIN_ACTUATION: -60
Z_P: 25
PITCH_D: 0
PITCH_I: 0.001
PITCH_I_LIMIT: 2.5
PITCH_MAX_ACTUATION: 20
PITCH_MIN_ACTUATION: -20
PITCH_P: 1
YAW_D: 1
YAW_I: 1
YAW_I_LIMIT: 1
YAW_MAX_ACTUATION: 20
YAW_MIN_ACTUATION: -20
YAW_P: 2