CONSTANT_DEPTH_FORCE: 0
X_D: 28
X_I: 0
X_I_LIMIT: 12
X_MAX_ACTUATION: 60
X_MIN_ACTUATION: -60
X_P: 22
Y_D: 15
Y_I: 0
Y_I_LIMIT: 6
Y_MAX_ACTUATION: 60
Y_MIN_ACTUATION: -60
Y_P: 22
Z_D: 10
Z_I: 0.25
Z_I_LIMIT: 2
Z_MAX_ACTUATION: 60
Z_MIN_ACTUATION: -60
Z_P: 10
PITCH_D: 0
PITCH_I: 0.01
PITCH_I_LIMIT: 2.5
PITCH_MAX_ACTUATION: 20
PITCH_MIN_ACTUATION: -20
PITCH_P: 4
YAW_D: 0
YAW_I: 0.01
YAW_I_LIMIT: 2.5
YAW_MAX_ACTUATION: 20
YAW_MIN_ACTUATION: -20
YAW_P: 4