CONSTANT_DEPTH_FORCE: 10
X_D: 40
X_I: 0.25
X_I_LIMIT: 12
X_MAX_ACTUATION: 60
X_MIN_ACTUATION: -60
X_P: 48
Y_D: 40
Y_I: 0.25
Y_I_LIMIT: 12
Y_MAX_ACTUATION: 60
Y_MIN_ACTUATION: -60
Y_P: 48
Z_D: 0
Z_I: 0.2
Z_I_LIMIT: 2
Z_MAX_ACTUATION: 60
Z_MIN_ACTUATION: -60
Z_P: 25
PITCH_D: 0
PITCH_I: 0.001
PITCH_I_LIMIT: 2.5
PITCH_MAX_ACTUATION: 20
PITCH_MIN_ACTUATION: -20
PITCH_P: 1
YAW_D: 50
YAW_I: 25
YAW_I_LIMIT: 2.5
YAW_MAX_ACTUATION: 20
YAW_MIN_ACTUATION: -20
YAW_P: 15