CONSTANT_DEPTH_FORCE: 10
X_D: 15
X_I: 0.25
X_I_LIMIT: 12
X_MAX_ACTUATION: 60
X_MIN_ACTUATION: -60
X_P: 7
Y_D: 15
Y_I: 0.25
Y_I_LIMIT: 12
Y_MAX_ACTUATION: 60
Y_MIN_ACTUATION: -60
Y_P: 7
Z_D: 0
Z_I: 0.5
Z_I_LIMIT: 2
Z_MAX_ACTUATION: 60
Z_MIN_ACTUATION: -60
Z_P: 20
PITCH_D: 0
PITCH_I: 0.001
PITCH_I_LIMIT: 2.5
PITCH_MAX_ACTUATION: 20
PITCH_MIN_ACTUATION: -20
PITCH_P: 1
YAW_D: 0
YAW_I: 0.1
YAW_I_LIMIT: 2.5
YAW_MAX_ACTUATION: 20
YAW_MIN_ACTUATION: -20
YAW_P: 0.2