CONSTANT_DEPTH_FORCE: 0
X_D: 30
X_I: 0
X_I_LIMIT: 4
X_MAX_ACTUATION: 100
X_MIN_ACTUATION: -100
X_P: 25
Y_D: 15
Y_I: 0
Y_I_LIMIT: 6
Y_MAX_ACTUATION: 100
Y_MIN_ACTUATION: -100
Y_P: 22
Z_D: 10
Z_I: 0.25
Z_I_LIMIT: 2
Z_MAX_ACTUATION: 100
Z_MIN_ACTUATION: -100
Z_P: 45
YAW_D: 0
YAW_I: 0
YAW_I_LIMIT: 2.5
YAW_MAX_ACTUATION: 100
YAW_MIN_ACTUATION: -100
YAW_P: 0.125