CONSTANT_DEPTH_FORCE: 0
X_D: 2.7
X_I: 1.85
X_I_LIMIT: 6
X_MAX_ACTUATION: 50
X_MIN_ACTUATION: -48
X_P: 40
Y_D: 2.7
Y_I: 0
Y_I_LIMIT: 4
Y_MAX_ACTUATION: 48
Y_MIN_ACTUATION: -60
Y_P: 40
Z_D: 10
Z_I: 1
Z_I_LIMIT: -2
Z_MAX_ACTUATION: 58
Z_MIN_ACTUATION: -60
Z_P: 32
ROLL_D: 0
ROLL_I: 0
ROLL_I_LIMIT: 0
ROLL_MAX_ACTUATION: 0
ROLL_MIN_ACTUATION: 8
ROLL_P: 0
PITCH_D: 0
PITCH_I: 0.001
PITCH_I_LIMIT: 2.5
PITCH_MAX_ACTUATION: 20
PITCH_MIN_ACTUATION: -20
PITCH_P: 1
YAW_D: 0.6
YAW_I: 2
YAW_I_LIMIT: 1
YAW_MAX_ACTUATION: 20
YAW_MIN_ACTUATION: -20
YAW_P: 0.5