port: [0.55, 0, 0, 0, 0, 0]
starboard: [0.5, 0, 0, 0, 0, 0]
front_heading: [0, -0.55, 0, 0, 0, -0.55]
back_heading: [0, -0.45, 0, 0, 0, 0.45]
front_depth: [0, 0, 0.5, 0, 0, 0]
back_depth: [0, 0, 0.5, 0, 0, 0]
