port: [55, 0, 0, 55, 0, 0]
starboard: [50, 0, 0, -50, 0, 0]
front_depth: [0, 0, 50, 0, 0, 50]
back_depth: [0, 0, 50, 0, 0, -50]
front_heading: [0, -55, 0, 0, -55, 0]
back_heading: [0, -45, 0, 0, 45, 0]